### ISSUE TITLE
Round the grade value

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/larasta#130]
![image](https://user-images.githubusercontent.com/7465241/115260759-5405c380-a133-11eb-8bcb-a9efda8d828d.png)

**Comment by imfeldd** [comment]
By the way, the input for the grade has a step of `0.5`, but there are multiple grades in the DB with grades not multiples of `0.5` (e.g. `5.3` or `4.9`). Should the step of the input set to `0.1`?
