### ISSUE TITLE
Attribution d'un stage

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/larasta#85]
Il n'y a aucun moyen d'attribuer une place de stage à un élève !!!

Dans la page d'édition du stage, si le stage n'est pas attribué, il faut mettre une liste déroulante contenant tous les élèves de la volée correspondante et n'ayant pas de stage

**Comment by CyrilGoldenschue** [comment]
actuellement quand on clique sur le bouton "créer", qui permet de mettre à jour les informations d'un stage, la mise à jour de l'élève n'est pas prise en compte.

**Comment by CyrilGoldenschue** [comment]
Le formulaire ne prenais pas en compte la zone lié à l'étudiant j'ai donc incorporé le titre dans la balise <form>
